### ISSUE TITLE
Using $this when not in object context

### ISSUE THREAD

**Issue by haceneouserir** [digikraaft/laravel-review-rating#10]
I installed the "laravel-review-rating" package correctly, but I have a problem when using the review() method in my controller I get this error: "Use $this when it is not in the context of the object", after tracing the error I found result of this line numbered 37 from the HasReviewRating attribute, "return $this->createReview($review, $author, $rating, $title);",
Please can anyone help me?

**Comment by timoladoyinbo** [comment]
Hello @haceneouserir can you share the code in your controller and your User model

**Comment by timoladoyinbo** [comment]
Hello @haceneouserir this is now fixed in this [PR ](https://github.com/digikraaft/laravel-review-rating/pull/12). A new release has also been tagged [here](https://github.com/digikraaft/laravel-review-rating/tree/v2.3.1).
