### ISSUE TITLE
Not install in Laravel 11 (Your requirements could not be resolved to an installable set of packages.)

### ISSUE THREAD

**Issue by sahilcygner** [digikraaft/laravel-review-rating#16]
composer require digikraaft/laravel-review-rating
./composer.json has been updated
Running composer update digikraaft/laravel-review-rating
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - digikraaft/laravel-review-rating[v1.0.0, v2.0.0, ..., v2.0.1] require php ^7.4 -> your php version (8.2.7) does not satisfy that requirement.
    - digikraaft/laravel-review-rating v2.1.0 requires php ^7.4|8.0.* -> your php version (8.2.7) does not satisfy that requirement.
    - digikraaft/laravel-review-rating v2.2.0 requires laravel/framework ^8.0 -> found laravel/framework[v8.0.0, ..., v8.83.27] but it conflicts with your root composer.json require (^11.0).
    - digikraaft/laravel-review-rating[v2.3.0, ..., v2.3.1] require laravel/framework ^8.0|^9.0 -> found laravel/framework[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but it conflicts with your root composer.json require (^11.0).
    - digikraaft/laravel-review-rating v3.0.0 requires laravel/framework ^10.0 -> found laravel/framework[v10.0.0, ..., v10.48.10] but it conflicts with your root composer.json require (^11.0).
    - Root composer.json requires digikraaft/laravel-review-rating * -> satisfiable by digikraaft/laravel-review-rating[v1.0.0, v2.0.0, ..., v2.3.1, v3.0.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require digikraaft/laravel-review-rating:*" to figure out if any version is installable, or "composer require digikraaft/laravel-review-rating:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by trupen1010** [comment]
> @sahilcygner Created a PR to fix this.

Can you please update this in Composer, I can't build it from your branch.
