### ISSUE TITLE
avarageRating fails on model

### ISSUE THREAD

**Issue by DanielRTRD** [digikraaft/laravel-review-rating#3]
´´´
SQLSTATE[42000]: Syntax error or access violation: 1140 Mixing of GROUP columns (MIN(),MAX(),COUNT(),...) with no GROUP columns is illegal if there is no GROUP BY clause (SQL: select ROUND(AVG(rating), 1) AS averageRating from `reviews` where `reviews`.`model_id` = 2 and `reviews`.`model_id` is not null and `reviews`.`model_type` = App\Models\Resource order by `id` desc)
´´´

PHP 8.0.12
Laravel 8.78.1

**Comment by qodictive** [comment]
Hi Daniel,
I have the same issue. I did something cause i was in a hurry (i don't know if it's correct or wise) and it's working.
I edited the Trait HasReviewRating (line 136) as follows and it worked

I replaced this 
      /*return $this->reviews()
                ->selectRaw('AVG(rating) AS averageRating')
                ->pluck('averageRating')
                ->first(); */
with
            **return round($this->reviews()->avg('rating'));**



> ´´´ SQLSTATE[42000]: Syntax error or access violation: 1140 Mixing of GROUP columns (MIN(),MAX(),COUNT(),...) with no GROUP columns is illegal if there is no GROUP BY clause (SQL: select ROUND(AVG(rating), 1) AS averageRating from `reviews` where `reviews`.`model_id` = 2 and `reviews`.`model_id` is not null and `reviews`.`model_type` = App\Models\Resource order by `id` desc) ´´´
> 
> PHP 8.0.12 Laravel 8.78.1

**Comment by DanielRTRD** [comment]
@qodictive Thanks for checking and responding! I can create a PR for that! 👍🏻

**Comment by qodictive** [comment]
No problem, I also had to make changes on the similar returns in the code as i might need to call ratings between periods and works great

**Comment by timoladoyinbo** [comment]
Thanks @DanielRTRD and @qodictive I will tag a new release now

**Comment by DanielRTRD** [comment]
> Thanks @DanielRTRD and @qodictive I will tag a new release now

Wait for my PR to be done and fully tested :D

**Comment by timoladoyinbo** [comment]
Yes @DanielRTRD  I just noticed some tests were failing. Thanks
